/*
    Yep, it's a guessing game in C!
*/
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

int main()
{

    printf("Welcome to the Guess the Number game. You have 5 tries to guess the number generated by this program. It will be between 0 and 20.\n");

    srand(time(NULL));
    int random_number = rand() % 21;
    int guess = -1;
    int tries = 5;

    while ((guess != random_number) && (tries > 0))
    {
        printf("You have %d tries left.\n", tries);
        printf("Enter a guess: ");
        scanf("%d", &guess);

        if (guess < 0 || guess > 20)
        {
            printf("Number out of range! Still counts as a guess :(\n");
            --tries;
        }
        else if (guess > random_number)
        {
            printf("The number is lower than your guess.\n");
            --tries;
        }
        else if (guess < random_number)
        {
            printf("The number is higher than your guess.\n");
            --tries;
        } 
        else if (guess == random_number)
        {
            printf("\n You guessed correctly!\n");
            break;
        }
        else
        {
            printf("Nope, that didn't work!");
            --tries;
        }
    }

    if (tries < 1)
    {
        printf("\n Game Over!\n");
    }

}
