FROM python:3.11.0b3-alpine
WORKDIR /app

COPY needs_the_validator/app.py shared/requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]