spring:
  application:
    name: trading-engine
  cloud:
    loadbalancer:
      retry:
        enabled: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: true
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 5000
  ConnectTimeout: 2000

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        retryer: com.netflix.feign.Retryer.Default
  request:
    compression: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans