spring:
  application:
    name: trading-engine

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans